name: "otel-profiling"

services:
  agent:
    build:
      context: .
      args:
        - arch=${ARCH:?error}
    privileged: true
    pid: "host"
    environment:
      DD_SITE: ${DD_SITE:-datadoghq.com}
      DD_EXPERIMENTAL_LOCAL_SYMBOL_UPLOAD: ${DD_EXPERIMENTAL_LOCAL_SYMBOL_UPLOAD:-false}
    volumes:
      - .:/agent
      - /var/run/docker.sock:/var/run/docker.sock:ro
    secrets:
      - dd-api-key
    command: ['/bin/sh', '-c', 'export DD_API_KEY=$$(cat /run/secrets/dd-api-key); sudo mount -t debugfs none /sys/kernel/debug && make && sudo -E /agent/otel-profiling-agent -tags "service:${OTEL_PROFILING_AGENT_SERVICE:-otel-profiling-agent-dev};remote_symbols:yes" -collection-agent "http://datadog-agent:8126" -reporter-interval ${OTEL_PROFILING_AGENT_REPORTER_INTERVAL:-60s} -samples-per-second 20 -save-cpuprofile']

  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    cgroup: host
    environment:
      DD_SITE: ${DD_SITE:-datadoghq.com}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    secrets:
      - dd-api-key
    entrypoint: ['/bin/sh', '-c', 'export DD_API_KEY=$$(cat /run/secrets/dd-api-key) ; /bin/entrypoint.sh']

secrets:
  dd-api-key:
    environment: DD_API_KEY
