name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: datadog/otel-profiling-agent
      RELEASE_VERSION: ${{ github.ref_name }}
    needs: build
    name: Release
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: write
      packages: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          annotations: |
            org.opencontainers.image.description=The Datadog OpenTelemetry Profiling Agent is a full-host profiler that collects and sends profiling data to Datadog
            org.opencontainers.image.vendor=Datadog
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Create assets
        run: |
          tar czf otel-profiling-agent-${RELEASE_VERSION}-aarch64.tar.gz -C agent-aarch64 .
          tar czf otel-profiling-agent-${RELEASE_VERSION}-x86_64.tar.gz -C agent-x86_64 .
          sha256sum otel-profiling-agent-${RELEASE_VERSION}-aarch64.tar.gz otel-profiling-agent-${RELEASE_VERSION}-x86_64.tar.gz > sha256sums.txt
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "otel-profiling-agent-v*.tar.gz,sha256sums.txt"
          allowUpdates: true
          omitBody:  true
          draft: true
          tag: ${{ env.RELEASE_VERSION }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.release
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
